# Site settings
title: Gilmar Silva
description: 'Security Reseacher'
url: ''
baseurl: ''
host: 0.0.0.0
port: 8080
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gilmar Silva'
  email: gilmar@fireshellsecurity.team
  twitter_username: gilmarsilva_
  facebook_username: gilmazin
  github_username:  heavenh
  linkedin_username:  heaven

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
